version: '3.8'

services:
  db:
    image: postgres:15
    container_name: fastapi_test_db
    restart: always
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: dbnametest

volumes:
  postgres_data:


